apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.database.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.database.name | quote }}
  MARIADB_USER: {{ .Values.database.user | quote }}
  MARIADB_PASSWORD: {{ .Values.database.password | quote }}
